export { EmbeddedStorage } from "./storage/embedded-storage.js";
export { decodeBinaryRecord, encodeBinaryRecord } from "./core/binary-codec.js";
export {
  buildGvqlGraphIndex,
  encodedValueToJs,
  executeGvqlStatement,
  jsValueToEncoded,
  matchBindings,
  parseGvql,
  propertyKey,
  propertyIndexKey,
  referencedEdges,
  visitEncodedNode,
} from "./gvql/gvql.js";
export type {
  GvqlGraphIndexBuildOptions,
  GvqlAggregateFunction,
  GvqlAdvancedGraphIndex,
  GvqlArithmeticOperator,
  GvqlBinding,
  GvqlCompareOperator,
  GvqlDirection,
  GvqlEdgePattern,
  GvqlExecutableContext,
  GvqlExecutionOptions,
  GvqlGraphEdge,
  GvqlGraphIndex,
  GvqlGraphNode,
  GvqlLiteral,
  GvqlLogicalOperator,
  GvqlMatchPattern,
  GvqlMutationPreview,
  GvqlMutationResult,
  GvqlNodePattern,
  GvqlOrderBy,
  GvqlPathExpression,
  GvqlPredicate,
  GvqlQueryResult,
  GvqlResult,
  GvqlReturnExpression,
  GvqlSetExpression,
  GvqlSetValueExpression,
  GvqlStatement,
  GvqlStatementKind,
  GvqlWhereClause,
} from "./gvql/gvql.js";
export {
  GraphVaultModule,
  GraphVaultTransactional,
  GRAPHVAULT_MANAGER,
  GRAPHVAULT_OPTIONS,
} from "./integrations/nest.js";
export type {
  DynamicModuleLike,
  GraphVaultModuleAsyncOptions,
  GraphVaultModuleOptions,
  GraphVaultTransactionalOptions,
  NestProvider,
} from "./integrations/nest.js";
export {
  GraphVaultError,
  OptimisticLockError,
  StorageLockError,
  StorageNotStartedError,
  ReadonlyStorageError,
  TransactionScopeError,
  UnknownTypeError,
} from "./core/errors.js";
export { startStorage } from "./storage/factory.js";
export { LazyArrayList } from "./lazy/lazy-array-list.js";
export { lazy, LazyRef } from "./lazy/lazy-ref.js";
export { PersistentCache } from "./cache/persistent-cache.js";
export type { PersistentCacheRoot } from "./cache/persistent-cache.js";
export { GraphSerializer, ObjectIdRegistry, TypeRegistry } from "./core/serializer.js";
export {
  copyStorageTargetTree,
  EncryptedStorageTarget,
  HttpStorageTarget,
  LocalFilesystemTarget,
  MemoryStorageTarget,
  S3StorageTarget,
  SqlStorageTarget,
} from "./storage/storage-target.js";
export type {
  HttpStorageTargetOptions,
  EncryptedStorageTargetOptions,
  LocalFilesystemTargetOptions,
  S3Body,
  S3ListObjectsRequest,
  S3ListObjectsResponse,
  S3ObjectRequest,
  S3PutObjectRequest,
  S3StorageClient,
  S3StorageTargetOptions,
  SqlQueryResult,
  SqlStorageClient,
  SqlStorageTargetOptions,
} from "./storage/storage-target.js";
export { StorageManager } from "./storage/storage-manager.js";
export { assessStorageSafety } from "./storage/storage-safety.js";
export type { StorageSafetyAssessmentInput } from "./storage/storage-safety.js";
export { Storer } from "./storage/storer.js";
export type {
  ClassConstructor,
  BackupResult,
  CompactionResult,
  GarbageCollectionResult,
  SerializedEnvelope,
  ObjectRecord,
  ParentIndexRecord,
  ParentReference,
  StorageAdvancedIndexDefinitionRecord,
  StorageAdvancedIndexRecord,
  StorageCompositeIndexDefinition,
  StorageExpressionIndexDefinition,
  StorageFullTextIndexDefinition,
  StorageIndexCondition,
  StorageIndexConditionOperator,
  StorageIndexDefinition,
  StorageIndexEdge,
  StorageIndexOptions,
  StorageIndexStatistics,
  StorageIndexRecord,
  StorageIndexVerificationResult,
  StorageRangeIndexDefinition,
  StorageIndexStatus,
  StorageIndexConsistency,
  StorageIndexMode,
  StorageTextIndexDefinition,
  StorageUniqueIndexDefinition,
  StorageManifest,
  TypeDictionary,
  TypeDictionaryEntry,
  TransactionRecord,
  WalCommitRecord,
  WalPrepareRecord,
  WalRecord,
  VerificationResult,
  MaintenanceResult,
  MaintenanceOptions,
  StorageManagerOptions,
  StorageCommitValidator,
  StorageHealthOptions,
  StorageHealthReport,
  StorageHealthStatus,
  StorageOperationsStatus,
  StorageSafetyIssue,
  StorageSafetyProfile,
  StorageSafetySeverity,
  StorageSafetyStatus,
  StorageStatus,
  SubtreeLoadOptions,
  SubtreeLoadResult,
  SubtreeReference,
  StorageTarget,
  StorageTargetLock,
  StorageLockOptions,
  StorageLockStrategy,
  StorageTransactionLogMode,
  StoreMetadata,
  StoreMode,
  GraphVaultTransactionContext,
  GraphVaultTransactionOptions,
  GraphVaultTransactionResult,
  SchemaMigrationMetadata,
  StorageMigrationDirection,
  StorageMigrationPlanStep,
  StorageMigrationResult,
  StorageMigrationStatus,
  StorageMigrationStepResult,
  StorageSchemaMigration,
  StorageSchemaMigrationContext,
  TransactionLockMode,
  StorageWriteDurability,
  StorageWriteProfile,
  ObjectRecordWriteFormat,
  TypeRegistration,
} from "./core/types.js";
